version: "3.7"

networks:
  app:
    driver_opts:
      com.docker.network.bridge.name: br0
    ipam:
      driver: default
      config:
        - subnet: 172.72.0.0/30

services:
  app:
    build: ./build
    container_name: news_aismc_bid
    networks:
      app:
        ipv4_address: 172.72.0.2
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "./www:/www:rw"
      - "./config/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./config/php-fpm.conf:/etc/php/php-fpm.conf:ro"
      - "./config/php.ini:/etc/php/php.ini:ro"
    environment:
      - "TZ=UTC"

